# Generated by Django 3.1.2 on 2021-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_desc',
            field=models.CharField(default='', max_length=550),
        ),
    ]
