# Generated by Django 3.1.2 on 2021-06-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(),
        ),
    ]
